### ISSUE TITLE
Inquiry about "Non-Contrastive Self-Supervised Learning of Utterance-Level Speech Representations" paper code

### ISSUE THREAD

**Issue by Choddeok** [hyperion-ml/hyperion#130]
I read about "Non-Contrastive Self-Supervised Learning of Utterance-Level Speech Representations" paper this time. I read the paper so well that I could get a lot of information and study.

I'm contacting you because I don't have the code for paper git yet even though you wrote that you will upload the code to git on the paper. I'd like to study more about the research by looking at the thesis and code together, so can I ask when the code content will be uploaded?

Thank you.

**Comment by jesus-villalba** [comment]
Hi,
The recipe for DINO is in persephone-dino branch. We still haven't had time to merge it.
https://github.com/hyperion-ml/hyperion/tree/persephone-dino/egs/voxceleb/dinossl.v1

**Comment by Choddeok** [comment]
Thank you :)
I'll keep that in mind and study.
